### PR TITLE
feat: add favicon, icon, and apple-icon for the app

### PR DESCRIPTION
**Pull request by burhanharoon**
## Description

I have added a favicon, icon, and apple-icon for the `trello-clone` next app so that it looks nicer in production while following the best practices of `Next.js 13`
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style and structure of this project
- [x] My code follows the principles of clean code
- [x] My changes generate no new warnings, bugs or errors

### CODE REVIEW

**Comment by burhanharoon** [comment]
@0l1v3rr Please have a look at the changes. Thank you!

**Comment by 0l1v3rr** [comment]
> @0l1v3rr Please have a look at the changes. Thank you!

Hi,

Thanks for the contribution!

**Comment by burhanharoon** [comment]
@0l1v3rr Thanks you liked it, can you please add me as an `Assignee` in this PR?

**Comment by 0l1v3rr** [comment]
done! :)

**Pull request merged**
