### PR TITLE
fix: make favicon transparent

### PR DESCRIPTION
**Pull request by burhanharoon**
## Description

Made the favicon transparent so that it doesn't appear weird with a white background while viewing the website in dark mode.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style and structure of this project
- [x] My code follows the principles of clean code
- [x] My changes generate no new warnings, bugs or errors

### CODE REVIEW

**Comment by burhanharoon** [comment]
@0l1v3rr I have made the required changes, please have a look :)

**Comment by 0l1v3rr** [comment]
@burhanharoon could you resolve the conflict? I can't merge this.

**Comment by burhanharoon** [comment]
Sure I'll do that.

**Comment by 0l1v3rr** [comment]
@burhanharoon, I still can't merge because of the conflicts. I think the easiest solution would be to sync the main branch of your fork (which contains the favicon with the white bg) and work from there. Then you could make another PR without conflicts.

**Pull request closed without merging**
